"""fixed user model relationship a

Revision ID: 86cdbb859825
Revises: c90cccbcf5b8
Create Date: 2023-06-06 15:19:23.312016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cdbb859825'
down_revision = 'c90cccbcf5b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('microblog_posts_user_fkey', 'microblog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'microblog_posts', 'user', ['user_id'], ['id'])
    op.drop_column('microblog_posts', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'microblog_posts', type_='foreignkey')
    op.create_foreign_key('microblog_posts_user_fkey', 'microblog_posts', 'user', ['user'], ['id'])
    op.drop_column('microblog_posts', 'user_id')
    # ### end Alembic commands ###
