"""fixed

Revision ID: 9960694418cc
Revises: 86cdbb859825
Create Date: 2023-06-14 20:40:20.655389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9960694418cc'
down_revision = '86cdbb859825'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
