"""fixed user model relationship

Revision ID: c90cccbcf5b8
Revises: ca30de07d968
Create Date: 2023-06-06 15:16:53.517871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90cccbcf5b8'
down_revision = 'ca30de07d968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
