"""fixed user model

Revision ID: ca30de07d968
Revises: a4910cfc67f9
Create Date: 2023-06-06 15:13:43.055828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca30de07d968'
down_revision = 'a4910cfc67f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
